name: main workflow for common testing

on:
  pull_request:
    branches:
      - 'dev'
      - 'staging'
      - 'main'

jobs:
  format:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node modules
        run: npm ci

      - name: Lint
        run: npm run lint:check

      - name: Prettier
        run: npm run prettier:check

      - name: Jest
        run: npm run test
